### PR TITLE
fix: use correct variable name for model_id

### PR DESCRIPTION
**Pull request by paulschreiber**

### CODE REVIEW

**Comment by thskaggs** [comment]
I'm disinclined to make changes to DB_Module.py or ANN_Module.py. rosetta-soil is a wrapper around those files, which are from a different code base. I'd rather keep those file as they are.

**Comment by paulschreiber** [comment]
@thskaggs this doesn't look like it will work as written:
- there is no `model` variable (unless it's in the global scope), but that doesn't seem likely as…
- the `model_id` parameter is unused.

**Comment by thskaggs** [comment]
I agree that code must not work but it does not affect the interface to the Rosetta models provided by rosetta-soil.

The files ANN_Modul.py, DB_Module.py, and Rosetta.sqlite are from the authors of the academic papers documenting the Rosetta models. I prefer leaving those files alone for now.

**Comment by paulschreiber** [comment]
What repository are those files from? I am happy to share my fixes upstream with the authors.

**Pull request closed without merging**
